MKLEANBOOK_PATH := $(PWD)/..

AUTHORS = Joe Doe
TITLE = A mkleanbook example
COPYRIGHT_NOTICE = Copyright (C) 2016  Joe Doe\nReleased under Apache 2.0 license as described in the file LICENSE.
COMBINED_NAME = example

include $(MKLEANBOOK_PATH)/include.mk
