#+Title: Introduction
#+Author: Chris Hodapp

* Introduction

** What this is

The purpose of this tutorial is to introduce you to some pieces of
linear algebra and analytic geometry - and to use visual, interactive
programming in WebGL as the context to do so.

Most explanation is given alongside bits of code which run directly in
the browser.  To the right of this content (or possibly elsewhere,
depending on your browser), you'll see a pane with a couple tabs.  The
whole point of this pane is to let you play around with this code, and
see results immediately - without having to install an entire
development environment, without having to manually adapt equations or
pseudocode, without having to build an entire framework to test
something simple, and without having any real risk that you will
destroy anything.

# TODO: Give a simple WebGL example here

Everything about this tutorial is open source.  Further, the code
that's included here, and any code that you'll write, is all "real"
code written in a standard language that runs in countless other
places (with a little adaptation) - it's simply fragment shaders
written in GLSL ([[https://en.wikipedia.org/wiki/OpenGL_Shading_Language][OpenGL Shading Language]]).  That is, I didn't invent a
toy programming language or API for this tutorial.  On top of that,
nearly anything you write could be translated easily to many other
shading languages (e.g. [[https://en.wikipedia.org/wiki/Cg_(programming_language)][Cg]], [[https://en.wikipedia.org/wiki/High-level_shader_language][HLSL]], [[https://en.wikipedia.org/wiki/RenderMan_Shading_Language][RSL]]) that work very similarly, or
really to any other language.

# TODO: Supply GitHub link above.

** Requirements

To make full use of this, you'll require:

- A browser that [[https://en.wikipedia.org/wiki/WebGL#Support][supports WebGL]], and has enabled it
- A graphics card that is fast enough for the demos here

This assumes some background:

- Some familiarity with some form of general programming - something
  like C, C++, Java, or JavaScript.
- Some minimal background in graphics.  You should know that pixels
  are used to represent images on a computer, and how colors are
  represented.
- Some background in algebra and geometry.  You should know what a
  coordinate plane is.

** What this is not

This tutorial is not:

- An introduction to web programming in general - including with
  WebGL.  Other tutorials better serve that task, such as [[https://webglfundamentals.org/][WebGL
  Fundamentals]].  This tutorial uses a fairly small part of what WebGL
  provides.
- A rigorous, formal treatment of the topic.  However, I do try to
  link to external resources of that sort where appropriate.
- An introduction into programming for those who have no experience
  whatsoever.
- Instructions for how to make a robust, high-quality and/or fast
  renderer.  That is another area completely.  For nearly any code I
  supply here, "real" renderers do it faster and better - but with
  orders of magnitude more complication.

** Credits & Acknowledgements

Most of the foundation of the code for this site is a heavily-adapted
version of [[https://github.com/leanprover/mkleanbook][mkleanbook]], which I discovered after liking the style and
paradigm of [[https://leanprover.github.io/introduction_to_lean/][An Introduction to Lean]] enough to want to mimic it.

The WebGL and editor portions of this site are thanks to [[https://github.com/gportelli/pocket.gl][pocket.gl]], a
modified version of which is embedded in the site.

Fabrice Castel's [[https://fabricecastel.github.io/blog/2015-08-03/main.html][series]] on sphere tracing, [[http://www.iquilezles.org/][Íñigo Quílez's website]], [[https://thebookofshaders.com/][The
Book of Shaders]], and Morgan McGuire's [[https://www.cs.williams.edu/~morgan/cs371-f14/reading/implicit.pdf][Numerical Methods for Ray
Tracing Implicitly Defined Surfaces]] were very helpful references in
the course of building the content of this site.  Particularly, the
sphere tracing example in section 3 is based heavily around Íñigo
Quílez's [[https://www.shadertoy.com/view/Xds3zN][Raymarching Primitives demo]].

# TODO: Either put license text here or make note of where to find it.
