MKLEANBOOK_PATH := $(PWD)/..

AUTHORS = Chris Hodapp
TITLE = CS6460 Demo Content
COPYRIGHT_NOTICE = Copyright (C) 2017  Chris Hodapp\nReleased under Apache 2.0 license as described in the file LICENSE.
COMBINED = example

include $(MKLEANBOOK_PATH)/include.mk
